version: '3'
services:
  web:
    image: ${DOCKER_USERNAME}/mousavi:latest
    container_name: mousavi
    volumes:
      - /home/mousavi/staticfiles:/app/staticfiles
      - /home/mousavi/media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    command: ["gunicorn", "mousavi.wsgi:application", "--bind", "0.0.0.0:8000"]
    restart: unless-stopped

