version: '3'
services:
  web:
    image: ${DOCKER_USERNAME}/mousavi:latest
    container_name: mousavi
    volumes:
      - /home/mousavi/staticfiles:/app/staticfiles
      - /home/mousavi/media:/app/media
    expose:
      - "8000"
    environment:
      - DEBUG=False
    command: ["gunicorn", "mousavi.wsgi:application", "--bind", "0.0.0.0:8000"]
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: mousavi_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/mousavi/staticfiles:/app/staticfiles
      - /home/mousavi/media:/home/mousavi/media
    depends_on:
      - web
    restart: unless-stopped
