# Generated by Django 5.2.8 on 2026-07-18 19:11

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='نامک (Slug)')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان برچسب')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='نامک (Slug)')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='نامک (Slug)')),
                ('excerpt', models.TextField(max_length=500, verbose_name='توضیح کوتاه (Excerpt)')),
                ('content', tinymce.models.HTMLField(verbose_name='محتوای مقاله')),
                ('thumbnail', models.ImageField(upload_to='blog/thumbnails/', verbose_name='تصویر شاخص')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین تصویر (Alt Text)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('meta_title', models.CharField(blank=True, max_length=250, verbose_name='عنوان سئو (Meta Title)')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات سئو (Meta Description)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('categories', models.ManyToManyField(related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_date'],
            },
        ),
    ]
