# Generated by Django 5.2.8 on 2026-07-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کتاب')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوای کامل')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک دانلود/مشاهده')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='تصویر کتاب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کتاب و جزوه',
                'verbose_name_plural': 'کتاب\u200cها و جزوه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان استراتژی')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوای کامل')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ویدیو/مشاهده')),
                ('image', models.ImageField(blank=True, null=True, upload_to='strategies/', verbose_name='تصویر استراتژی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'استراتژی',
                'verbose_name_plural': 'استراتژی\u200cها',
            },
        ),
    ]
