# Generated by Django 5.2.8 on 2026-07-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True, verbose_name='تاریخ')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
            ],
            options={
                'verbose_name': 'بازدید سایت',
                'verbose_name_plural': 'بازدیدهای سایت',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
