# Generated by Django 5.2.8 on 2026-07-18 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitevisit_book_views_strategy_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='تاریخ'),
        ),
    ]
