"""
Django settings for mousavi project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

# مسیر اصلی پروژه
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================
# تنظیمات امنیتی و عمومی
# ==============================
SECRET_KEY = 'django-insecure-4al&8q01fw#cm=^445ji*yumt92&jrcu7dj6x(@@du=ho47y$o'
DEBUG = True
ALLOWED_HOSTS = ['*']

# ==============================
# اپلیکیشن‌های فعال
# ==============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',

    # اپ‌های اضافه‌شده توسط ما
    'django.contrib.humanize',  # برای فرمت قشنگ عددها
    'main',                     # اپ اصلی سایت
    'prices',                   # اپ قیمت لحظه‌ای
    'blog',                     # وبلاگ
    'tinymce',                  # ادیتور متن پیشرفته
]

SITE_ID = 1

# ==============================
# میان‌افزارها (Middleware)
# ==============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.SiteVisitMiddleware',
]

ROOT_URLCONF = 'mousavi.urls'

# ==============================
# قالب‌ها (Templates)
# ==============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # مسیر فولدر قالب‌ها
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mousavi.wsgi.application'

# ==============================
# پایگاه داده (Database)
# ==============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ==============================
# تنظیمات رمز عبور
# ==============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ==============================
# تنظیمات زبان و زمان
# ==============================
LANGUAGE_CODE = 'fa-ir'   # فارسی
TIME_ZONE = 'Asia/Tehran'  # منطقه زمانی ایران
USE_I18N = True
USE_TZ = True

# ==============================
# فایل‌های استاتیک (CSS، JS، عکس‌ها)
# ==============================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# فایل‌های آپلودی (مدیا)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==============================
# کلید پیش‌فرض برای مدل‌ها
# ==============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================
# تنظیمات ویرایشگر متن (TinyMCE)
# ==============================
TINYMCE_DEFAULT_CONFIG = {
    'height': 400,
    'width': 'auto',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'silver',
    'plugins': '''
        textcolor save link image media preview codesample contextmenu
        table code lists fullscreen insertdatetime nonbreaking
        contextmenu directionality searchreplace wordcount visualblocks
        visualchars code fullscreen autolink lists charmap print hr
        anchor pagebreak
        ''',
    'toolbar1': '''
        fullscreen preview bold italic underline | fontselect,
        fontsizeselect | forecolor backcolor | alignleft alignright |
        aligncenter alignjustify | indent outdent | bullist numlist table |
        | link image media | codesample |
        ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
    'directionality': 'rtl',
}

# ==============================
# تنظیمات وب‌هوک ثبت‌نام کاربران
# ==============================
USER_SIGNUP_WEBHOOK_URL = 'https://carry-doctor-gentleman-lance.trycloudflare.com/webhook/user-signup'
# آدرس تست: 'https://carry-doctor-gentleman-lance.trycloudflare.com/webhook-test/user-signup'

