name: Build & Deploy Django App (Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mousavi:latest
            ${{ secrets.DOCKER_USERNAME }}/mousavi:${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Pulling new image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/mousavi:${{ github.sha }}

            echo "Stopping old container..."
            docker stop mousavi || true
            docker rm mousavi || true

            echo "Running new container..."
            docker run -d \
              --name mousavi \
              --restart unless-stopped \
              -p 8000:8000 \
              -v /home/mousavi/static:/app/staticfiles \
              -v /home/mousavi/media:/app/media \
              ${{ secrets.DOCKER_USERNAME }}/mousavi:${{ github.sha }}

            echo "Cleaning up old images..."
            docker image prune -af --filter "until=24h"

